### ISSUE TITLE
Only matches when word acted on is the first?

### ISSUE THREAD

**Issue by patcon** [ajacksified/hubot-plusplus#4] opened 2013-12-11 22:24 UTC
Not sure if this is a bug or not. We used to be able to say things before the word we wanted to act on, and now this doesn't work. For example:

https://www.evernote.com/shard/s27/sh/4ac66797-e5b4-4144-913e-3a362400a211/f157a2c2d02642bc4871f8ef986bb067

Is this intentional?

Also, not familiar with "passive groups" `(?:...)` and how they work. Can we use a regex block and annotate it to explain some of this for others who are poking around?

https://github.com/ajacksified/hubot-plusplus/blob/master/src/pluspplus.coffee#L31

**Comment by plukevdh** [comment] 2015-01-07 15:42
Is this a dupe of #2?

**Comment by patcon** [comment] 2015-01-07 19:32
They're both regex, but I think different issues to sort out. One is about ignoring (no match), and the other about misattribution of the plus'ed word (mismatching). Not even sure whether both are current issues though :)

**Comment by therealklanni** [comment] 2016-04-18 23:46
I think we can close this now, phrases are supported.

**Closed by therealklanni** 2016-04-18 23:46 UTC
